addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - gfortran
    - valgrind
    - gcc-4.7
    - g++-4.7
    - gfortran-4.7
    - gcc-4.8
    - g++-4.8
    - gfortran-4.8
    - gcc-4.9
    - g++-4.9
    - gfortran-4.9
    - gcc-5
    - g++-5
    - gfortran-5

env:
  - CC=gcc     CXX=g++     FC=gfortran     BML_OPENMP=no VERBOSE_MAKEFILE=yes
  - CC=gcc-4.7 CXX=g++-4.7 FC=gfortran-4.7 BML_OPENMP=no VERBOSE_MAKEFILE=yes
  - CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 BML_OPENMP=no VERBOSE_MAKEFILE=yes
  - CC=gcc-4.9 CXX=g++-4.9 FC=gfortran-4.9 BML_OPENMP=no VERBOSE_MAKEFILE=yes
  - CC=gcc-5   CXX=g++-5   FC=gfortran-5   BML_OPENMP=no VERBOSE_MAKEFILE=yes

before_script:
  - pip install --user codecov

script:
  - ./build.sh testing

after_success:
  - pwd
  - find "${PWD}" -type f -name '*.gcno' -exec ls -lh {} +
  - codecov
