# We build on a matrix across difference compiler versions. If we specify C or
# C++ for the language, then Travis-CI will export either the CC or CXX
# variable to the environment but not both. Setting the language to something
# other we avoid this behavior and drive the build matrix solely through the
# environment.
language: python

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - cmake
            - cmake-data
            - doxygen
            - g++-4.7
            - g++-4.8
            - g++-4.9
            - g++-5
            - g++-6
            - gcc-4.7
            - gcc-4.8
            - gcc-4.9
            - gcc-5
            - gcc-6
            - gfortran
            - gfortran-4.7
            - gfortran-4.8
            - gfortran-4.9
            - gfortran-5
            - gfortran-6
            - indent
            - texlive
            - valgrind

env:
    - CC=gcc-4.7 CXX=g++-4.7 FC=gfortran-4.7 GCOV=gcov-4.7 BML_OPENMP=no  COMMAND=testing
    - CC=gcc-4.7 CXX=g++-4.7 FC=gfortran-4.7 GCOV=gcov-4.7 BML_OPENMP=yes COMMAND=testing
    - CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 GCOV=gcov-4.8 BML_OPENMP=no  COMMAND=testing
    - CC=gcc-4.8 CXX=g++-4.8 FC=gfortran-4.8 GCOV=gcov-4.8 BML_OPENMP=yes COMMAND=testing
    - CC=gcc-4.9 CXX=g++-4.9 FC=gfortran-4.9 GCOV=gcov-4.9 BML_OPENMP=no  COMMAND=testing
    - CC=gcc-4.9 CXX=g++-4.9 FC=gfortran-4.9 GCOV=gcov-4.9 BML_OPENMP=yes COMMAND=testing
    - CC=gcc-5   CXX=g++-5   FC=gfortran-5   GCOV=gcov-5   BML_OPENMP=no  COMMAND=testing
    - CC=gcc-5   CXX=g++-5   FC=gfortran-5   GCOV=gcov-5   BML_OPENMP=yes COMMAND=testing
    - CC=gcc-6   CXX=g++-6   FC=gfortran-6   GCOV=gcov-6   BML_OPENMP=no  COMMAND=testing
    - CC=gcc-6   CXX=g++-6   FC=gfortran-6   GCOV=gcov-6   BML_OPENMP=yes COMMAND=testing
    - BML_OPENMP=no  VERBOSE_MAKEFILE=yes COMMAND=docs
    - BML_OPENMP=no  VERBOSE_MAKEFILE=yes COMMAND=indent

before_script:
    - pip install codecov

script:
    - CMAKE_BUILD_TYPE=Debug BUILD_SHARED_LIBS=yes VERBOSE_MAKEFILE=yes ./build.sh ${COMMAND}

after_success:
    - codecov --gcov-exec ${GCOV}
